GLOBAL CYBERSECURITY THREAT ANALYSIS (2015–2024)

- Project Objective:

    - Analyze cybersecurity threats from 2015 to 2024.
    - Identify common attack types and attack methods.
    - Find out which industries and countries are most affected.
    - Examine the impact of attacks through financial losses and data breaches.
    - Explore the relationship between attack severity, response time, and mitigation strategies.
    - Discover key trends and insights from cybersecurity incidents.

STEP01 : IMPORTING REQUIRED LIBRARIES

- Pandas & Numpy for data manipulation
- Matplotlib & Seaborn for Data Visualization
- SciPy for advanced statistical analysis
- Warnings for suppressing unnecessary warning messages

In [3]:
# Data Manipulation
import numpy as np 
import pandas as pd 

# Data Visualization
import matplotlib.pyplot as plt 
import seaborn as sns 

# Statistical Analysis
from scipy import stats

# Ignore Warnings
import warnings
warnings.filterwarnings('ignore')

STEP02: DATA LOADING

- Reading the CSV file and storing it in a DataFrame called 'df'

In [4]:
df = pd.read_csv("cybersecurity_dataset.csv")
df

,Country,Year,Attack Type,Target Industry,Financial Loss (in Million $),Number of Affected Users,Attack Source,Security Vulnerability Type,Defense Mechanism Used,Incident Resolution Time (in Hours)
0,China,2019,Phishing,Education,80.53,773169,Hacker Group,Unpatched Software,VPN,63
1,China,2019,Ransomware,Retail,62.19,295961,Hacker Group,Unpatched Software,Firewall,71
2,India,2017,Man-in-the-Middle,IT,38.65,605895,Hacker Group,Weak Passwords,VPN,20
3,UK,2024,Ransomware,Telecommunications,41.44,659320,Nation-state,Social Engineering,AI-based Detection,7
4,Germany,2018,Man-in-the-Middle,IT,74.41,810682,Insider,Social Engineering,VPN,68
...,...,...,...,...,...,...,...,...,...,...
2995,UK,2021,Ransomware,Government,51.42,190694,Unknown,Social Engineering,Firewall,52
2996,Brazil,2023,SQL Injection,Telecommunications,30.28,892843,Hacker Group,Zero-day,VPN,26
2997,Brazil,2017,SQL Injection,IT,32.97,734737,Nation-state,Weak Passwords,AI-based Detection,30
2998,UK,2022,SQL Injection,IT,32.17,379954,Insider,Unpatched Software,Firewall,9
2999,Germany,2021,SQL Injection,Retail,48.20,480984,Unknown,Zero-day,VPN,64

STEP03: DATASET INSPECTION

- In this step, I explore the dataset to understand its structure,
- data types, missing values, and basic patterns before analysis

In [5]:
# 01 Check shape of dataset (rows, columns)
# This tells how big the dataset is
data_shape = df.shape
print(f"1. Dataset Shape (rows, columns): {data_shape}\n")


# 02 View column names
# Helps understand what features are available
data_columns = df.columns
print(f"2. Dataset Columns:")
for col in data_columns:
    print(col)

1. Dataset Shape (rows, columns): (3000, 10)

2. Dataset Columns:
Country
Year
Attack Type
Target Industry
Financial Loss (in Million $)
Number of Affected Users
Attack Source
Security Vulnerability Type
Defense Mechanism Used
Incident Resolution Time (in Hours)

In [6]:
# 03 View first 5 rows
# Gives a quick idea of how data looks
df.head()

,Country,Year,Attack Type,Target Industry,Financial Loss (in Million $),Number of Affected Users,Attack Source,Security Vulnerability Type,Defense Mechanism Used,Incident Resolution Time (in Hours)
0,China,2019,Phishing,Education,80.53,773169,Hacker Group,Unpatched Software,VPN,63
1,China,2019,Ransomware,Retail,62.19,295961,Hacker Group,Unpatched Software,Firewall,71
2,India,2017,Man-in-the-Middle,IT,38.65,605895,Hacker Group,Weak Passwords,VPN,20
3,UK,2024,Ransomware,Telecommunications,41.44,659320,Nation-state,Social Engineering,AI-based Detection,7
4,Germany,2018,Man-in-the-Middle,IT,74.41,810682,Insider,Social Engineering,VPN,68

In [7]:
# 04 Get basic info about dataset
# Shows data types, non-null values, memory usage
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 10 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Country                              3000 non-null   object
 1   Year                                 3000 non-null   int64
 2   Attack Type                          3000 non-null   object
 3   Target Industry                      3000 non-null   object
 4   Financial Loss (in Million $)        3000 non-null   float64
 5   Number of Affected Users             3000 non-null   int64
 6   Attack Source                        3000 non-null   object
 7   Security Vulnerability Type          3000 non-null   object
 8   Defense Mechanism Used               3000 non-null   object
 9   Incident Resolution Time (in Hours)  3000 non-null   int64
dtypes: float64(1), int64(3), object(6)
memory usage: 234.5+ KB

In [8]:
# 05 Statistical summary of numeric columns
# Helps understand distribution (mean, min, max, etc.)
df.describe()

,Year,Financial Loss (in Million $),Number of Affected Users,Incident Resolution Time (in Hours)
count,3000.000000,3000.000000,3000.000000,3000.000000
mean,2019.570333,50.492970,504684.136333,36.476000
std,2.857932,28.791415,289944.084972,20.570768
min,2015.000000,0.500000,424.000000,1.000000
25%,2017.000000,25.757500,255805.250000,19.000000
50%,2020.000000,50.795000,504513.000000,37.000000
75%,2022.000000,75.630000,758088.500000,55.000000
max,2024.000000,99.990000,999635.000000,72.000000

In [9]:
# 06 Check missing values in each column
# Helps identify data quality issues
missing_values = df.isnull().sum()
print(f"1. Missing Values of Dataset(Column-wise):\n{missing_values}\n")


# 07 Check duplicate rows
# Ensures there is no repeated data
duplicate_count = df.duplicated().sum()
print(f"2. Duplicate Rows Count: {duplicate_count}")

1. Missing Values of Dataset(Column-wise):
Country                                0
Year                                   0
Attack Type                            0
Target Industry                        0
Financial Loss (in Million $)          0
Number of Affected Users               0
Attack Source                          0
Security Vulnerability Type            0
Defense Mechanism Used                 0
Incident Resolution Time (in Hours)    0
dtype: int64

2. Duplicate Rows Count: 0

In [18]:
# 08 Unique values in important columns
# Helps understand category diversity

print(f"Year:{df['Year'].nunique()}")
print(f"Attack Type:{df['Attack Type'].nunique()}")
print(f"Target Industry:{df['Target Industry'].nunique()}")
print(f"Attack Source:{df['Attack Source'].nunique()}")
print(f"Security Vulnerability Type:{df['Security Vulnerability Type'].nunique()}")
print(f"Defence Mechanism:{df['Defense Mechanism Used'].nunique()}")

Year:10
Attack Type:6
Target Industry:7
Attack Source:4
Security Vulnerability Type:4
Defence Mechanism:5

In [19]:
# 09 Frequency of categorical columns
# Shows most common categories in each column with their counts sorted in descending order

print(f"{df['Year'].value_counts().sort_index()}\n")
print(f"{df['Attack Type'].value_counts()}\n")
print(f"{df['Target Industry'].value_counts()}\n")
print(f"{df['Attack Source'].value_counts()}\n")
print(f"{df['Security Vulnerability Type'].value_counts()}\n")
print(f"{df['Defense Mechanism Used'].value_counts()}\n")

Year
2015    277
2016    285
2017    319
2018    310
2019    263
2020    315
2021    299
2022    318
2023    315
2024    299
Name: count, dtype: int64

Attack Type
DDoS                 531
Phishing             529
SQL Injection        503
Ransomware           493
Malware              485
Man-in-the-Middle    459
Name: count, dtype: int64

Target Industry
IT                    478
Banking               445
Healthcare            429
Retail                423
Education             419
Telecommunications    403
Government            403
Name: count, dtype: int64

Attack Source
Nation-state    794
Unknown         768
Insider         752
Hacker Group    686
Name: count, dtype: int64

Security Vulnerability Type
Zero-day              785
Social Engineering    747
Unpatched Software    738
Weak Passwords        730
Name: count, dtype: int64

Defense Mechanism Used
Antivirus             628
VPN                   612
Encryption            592
Firewall              585
AI-based Detection    583
Name: count, dtype: int64

DATASET INSPECTION SUMMARY:

- The dataset has 3000 rows and 10 columns related to cybersecurity attacks from 2015–2024
- It includes both categorical features (Country, Attack Type, Industry, Attack Source, etc.) and numerical features (Financial Loss, Affected Users, Resolution Time)
- Data types are correct and the dataset is clean and well-structured

- There are no missing values or duplicate records
- Financial loss and number of affected users are very different across attacks, meaning some attacks are small while others cause a lot of damage and affect many people

- Different attack types, industries, and sources appear in almost equal amounts, so no single type clearly dominates the data.
- The data is spread evenly across years, with an average around 2019

- Overall, the dataset appears to be well-balanced and clean, suggesting it may be synthetically generated or curated for analytical and machine learning purposes

- Still, it is good for EDA and can provide meaningful insights into cybersecurity trends and patterns